"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getTargetRunId = exports.getOctokit = exports.getAccessToken = exports.uniqueArray = void 0;
const github_1 = require("@actions/github");
const core_1 = require("@actions/core");
const uniqueArray = (array) => [...new Set(array)];
exports.uniqueArray = uniqueArray;
const getAccessToken = (required) => core_1.getInput('GITHUB_TOKEN', { required });
exports.getAccessToken = getAccessToken;
const getOctokit = (token) => github_1.getOctokit(token !== null && token !== void 0 ? token : exports.getAccessToken(true), {});
exports.getOctokit = getOctokit;
const getTargetRunId = (context) => /^\d+$/.test(core_1.getInput('TARGET_RUN_ID')) ? Number(core_1.getInput('TARGET_RUN_ID')) : context.runId;
exports.getTargetRunId = getTargetRunId;
